
[workspace]
authors = ["Miki Vanoušek <vanousekmikulas@gmail.com>"]
channels = ["conda-forge", "aihabitat"]
name = "pytorch_playground"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]


[system-requirements]
cuda = "12.2"


[dependencies]
python = "*"
pytorch-gpu = "*"
pytorch="*"
cuda-version = "12.2.*"
requests = ">=2.32.3,<3"
transformers = ">=4.49.0,<5"
ipython = ">=9.0.2,<10"
ipykernel = ">=6.29.5,<7"
ipywidgets = ">=8.1.7,<9"
sentencepiece = ">=0.2.0,<0.3"
protobuf = ">=5.28.2,<6"
seaborn = ">=0.13.2,<0.14"
pip = ">=25.1.1,<26"
cuda-toolkit = ">=12.2.2,<13"
wandb = ">=0.20.0,<0.21"

